require('options')
require('impatient')
require('plugins')
require('keymaps')
require('autocmd')
require('after.lualine')
require('after.zen-mode')
require('after.nvim-tree')
require('after.toggleterm')
require('after.cmp')
require('after.treesitter')
require('after.telescope')
require('after.lspconfig')
vim.cmd [[colorscheme PaperColor]]
vim.opt.background = 'dark'
