require('options')
require('impatient').enable_profile()
require('plugins')
require('keymaps')
require('autocmd')
require('plugins.lualine')
require('plugins.zen-mode')
require('plugins.nvim-tree')
require('plugins.toggleterm')
require('plugins.cmp')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.lspconfig')
vim.cmd [[colorscheme PaperColor]]
