require('options')
require('impatient')
require('plugins')
require('keymaps')
require('autocmd')
require('after.plugins.lualine')
require('after.plugins.zen-mode')
require('after.plugins.nvim-tree')
require('after.plugins.toggleterm')
require('after.plugins.cmp')
require('after.plugins.treesitter')
require('after.plugins.telescope')
require('after.plugins.lspconfig')
vim.cmd [[colorscheme PaperColor]]
vim.opt.background = 'dark'
