#! /bin/sh

##############
# Auto Start #
##############

# start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# restore wallpaper
/home/rasul/.fehbg &
# polybar starter
.config/polybar/launch.sh & 
# start polkit
polkit-dumb-agent &
# set the cursor
xsetroot -cursor_name left_ptr & 
# set key repeat and delay
xset r rate 330 40 &
# lock screen after 5 mins and suspend 10 mins after that
/home/rasul/sources/scripts/locknsleep.sh &
# notfication deamon
killall -q  dunst;  dunst &
# set keyboard layout changer key combination
setxkbmap -layout 'us,az' -option 'grp:alt_space_toggle' &
# start clipboard manager
clipmenud &

###########
# Configs #
###########

bspc monitor -d 1 2 3 4 5 6 7 8 9 󰎇

bspc config border_width         2
bspc config window_gap			 0
bspc config active_border_color "#657B83"
bspc config normal_border_color "#002b36"
bspc config presel_feedback_color "#586e75"
# bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		      28

#########
# Rules #
#########

bspc rule -a Timeshift-gtk state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a qt5ct state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a kitty:scratch sticky=on layer=above \
rectangle=720x480+600+28 state=floating
bspc rule -a Galculator state=floating rectangle=360x480+1532+28 layer=above
